using Robust.Client.ResourceManagement;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.State;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Map;
using Serilog;
using System.Numerics;

namespace Content.Client.Damage;

[GenerateTypedNameReferences]
public sealed partial class StaminaUI : UIWidget
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private float _scale = 3.0f;
    private readonly float _maxWidth;


    public StaminaUI()
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        ChargeBar.BackgroundStyleBoxOverride = new StyleBoxTexture()
        {
            Texture = _resourceCache.GetResource<TextureResource>("/Textures/Interface/stamina/stamina_bar.png"),
            TextureScale = new Vector2(_scale, _scale),
        };
        ChargeBar.ForegroundStyleBoxOverride = new StyleBoxTexture()
        {
            Texture = _resourceCache.GetResource<TextureResource>("/Textures/Interface/stamina/stamina_bar_value.png"),
            TextureScale = new Vector2(_scale, _scale),
        };
    }

    public void SetValue(float value)
    {
        ChargeBar.Value = value;
    }
}
